/**
 *
 *  Allgroup.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Allgroup.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::koi;

const std::string Allgroup::Cols::_id = "id";
const std::string Allgroup::Cols::_groupname = "groupname";
const std::string Allgroup::Cols::_groupdesc = "groupdesc";
const std::string Allgroup::primaryKeyName = "id";
const bool Allgroup::hasPrimaryKey = true;
const std::string Allgroup::tableName = "allgroup";

const std::vector<typename Allgroup::MetaData> Allgroup::metaData_={
{"id","int32_t","int",4,1,1,1},
{"groupname","std::string","varchar(50)",50,0,0,1},
{"groupdesc","std::string","varchar(200)",200,0,0,0}
};
const std::string &Allgroup::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Allgroup::Allgroup(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["groupname"].isNull())
        {
            groupname_=std::make_shared<std::string>(r["groupname"].as<std::string>());
        }
        if(!r["groupdesc"].isNull())
        {
            groupdesc_=std::make_shared<std::string>(r["groupdesc"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            groupname_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            groupdesc_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Allgroup::Allgroup(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            groupname_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            groupdesc_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

Allgroup::Allgroup(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("groupname"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["groupname"].isNull())
        {
            groupname_=std::make_shared<std::string>(pJson["groupname"].asString());
        }
    }
    if(pJson.isMember("groupdesc"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["groupdesc"].isNull())
        {
            groupdesc_=std::make_shared<std::string>(pJson["groupdesc"].asString());
        }
    }
}

void Allgroup::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            groupname_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            groupdesc_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void Allgroup::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("groupname"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["groupname"].isNull())
        {
            groupname_=std::make_shared<std::string>(pJson["groupname"].asString());
        }
    }
    if(pJson.isMember("groupdesc"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["groupdesc"].isNull())
        {
            groupdesc_=std::make_shared<std::string>(pJson["groupdesc"].asString());
        }
    }
}

const int32_t &Allgroup::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Allgroup::getId() const noexcept
{
    return id_;
}
void Allgroup::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Allgroup::PrimaryKeyType & Allgroup::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Allgroup::getValueOfGroupname() const noexcept
{
    static const std::string defaultValue = std::string();
    if(groupname_)
        return *groupname_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Allgroup::getGroupname() const noexcept
{
    return groupname_;
}
void Allgroup::setGroupname(const std::string &pGroupname) noexcept
{
    groupname_ = std::make_shared<std::string>(pGroupname);
    dirtyFlag_[1] = true;
}
void Allgroup::setGroupname(std::string &&pGroupname) noexcept
{
    groupname_ = std::make_shared<std::string>(std::move(pGroupname));
    dirtyFlag_[1] = true;
}

const std::string &Allgroup::getValueOfGroupdesc() const noexcept
{
    static const std::string defaultValue = std::string();
    if(groupdesc_)
        return *groupdesc_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Allgroup::getGroupdesc() const noexcept
{
    return groupdesc_;
}
void Allgroup::setGroupdesc(const std::string &pGroupdesc) noexcept
{
    groupdesc_ = std::make_shared<std::string>(pGroupdesc);
    dirtyFlag_[2] = true;
}
void Allgroup::setGroupdesc(std::string &&pGroupdesc) noexcept
{
    groupdesc_ = std::make_shared<std::string>(std::move(pGroupdesc));
    dirtyFlag_[2] = true;
}
void Allgroup::setGroupdescToNull() noexcept
{
    groupdesc_.reset();
    dirtyFlag_[2] = true;
}

void Allgroup::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Allgroup::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "groupname",
        "groupdesc"
    };
    return inCols;
}

void Allgroup::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getGroupname())
        {
            binder << getValueOfGroupname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getGroupdesc())
        {
            binder << getValueOfGroupdesc();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Allgroup::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Allgroup::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getGroupname())
        {
            binder << getValueOfGroupname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getGroupdesc())
        {
            binder << getValueOfGroupdesc();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Allgroup::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getGroupname())
    {
        ret["groupname"]=getValueOfGroupname();
    }
    else
    {
        ret["groupname"]=Json::Value();
    }
    if(getGroupdesc())
    {
        ret["groupdesc"]=getValueOfGroupdesc();
    }
    else
    {
        ret["groupdesc"]=Json::Value();
    }
    return ret;
}

Json::Value Allgroup::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getGroupname())
            {
                ret[pMasqueradingVector[1]]=getValueOfGroupname();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getGroupdesc())
            {
                ret[pMasqueradingVector[2]]=getValueOfGroupdesc();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getGroupname())
    {
        ret["groupname"]=getValueOfGroupname();
    }
    else
    {
        ret["groupname"]=Json::Value();
    }
    if(getGroupdesc())
    {
        ret["groupdesc"]=getValueOfGroupdesc();
    }
    else
    {
        ret["groupdesc"]=Json::Value();
    }
    return ret;
}

bool Allgroup::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("groupname"))
    {
        if(!validJsonOfField(1, "groupname", pJson["groupname"], err, true))
            return false;
    }
    else
    {
        err="The groupname column cannot be null";
        return false;
    }
    if(pJson.isMember("groupdesc"))
    {
        if(!validJsonOfField(2, "groupdesc", pJson["groupdesc"], err, true))
            return false;
    }
    return true;
}
bool Allgroup::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Allgroup::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("groupname"))
    {
        if(!validJsonOfField(1, "groupname", pJson["groupname"], err, false))
            return false;
    }
    if(pJson.isMember("groupdesc"))
    {
        if(!validJsonOfField(2, "groupdesc", pJson["groupdesc"], err, false))
            return false;
    }
    return true;
}
bool Allgroup::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Allgroup::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 200)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 200)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
