/**
 *
 *  Groupuser.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Groupuser.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::db;

const std::string Groupuser::Cols::_groupid = "groupid";
const std::string Groupuser::Cols::_userid = "userid";
const std::string Groupuser::Cols::_grouprole = "grouprole";
const std::vector<std::string> Groupuser::primaryKeyName = {"groupid","userid"};
const bool Groupuser::hasPrimaryKey = true;
const std::string Groupuser::tableName = "groupuser";

const std::vector<typename Groupuser::MetaData> Groupuser::metaData_={
{"groupid","int32_t","int",4,0,1,1},
{"userid","int32_t","int",4,0,1,1},
{"grouprole","std::string","enum('creator','normal')",0,0,0,0}
};
const std::string &Groupuser::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Groupuser::Groupuser(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["groupid"].isNull())
        {
            groupid_=std::make_shared<int32_t>(r["groupid"].as<int32_t>());
        }
        if(!r["userid"].isNull())
        {
            userid_=std::make_shared<int32_t>(r["userid"].as<int32_t>());
        }
        if(!r["grouprole"].isNull())
        {
            grouprole_=std::make_shared<std::string>(r["grouprole"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            groupid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            grouprole_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Groupuser::Groupuser(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            groupid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            grouprole_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

Groupuser::Groupuser(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("groupid"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["groupid"].isNull())
        {
            groupid_=std::make_shared<int32_t>((int32_t)pJson["groupid"].asInt64());
        }
    }
    if(pJson.isMember("userid"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["userid"].isNull())
        {
            userid_=std::make_shared<int32_t>((int32_t)pJson["userid"].asInt64());
        }
    }
    if(pJson.isMember("grouprole"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["grouprole"].isNull())
        {
            grouprole_=std::make_shared<std::string>(pJson["grouprole"].asString());
        }
    }
}

void Groupuser::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            groupid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            grouprole_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void Groupuser::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("groupid"))
    {
        if(!pJson["groupid"].isNull())
        {
            groupid_=std::make_shared<int32_t>((int32_t)pJson["groupid"].asInt64());
        }
    }
    if(pJson.isMember("userid"))
    {
        if(!pJson["userid"].isNull())
        {
            userid_=std::make_shared<int32_t>((int32_t)pJson["userid"].asInt64());
        }
    }
    if(pJson.isMember("grouprole"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["grouprole"].isNull())
        {
            grouprole_=std::make_shared<std::string>(pJson["grouprole"].asString());
        }
    }
}

const int32_t &Groupuser::getValueOfGroupid() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(groupid_)
        return *groupid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Groupuser::getGroupid() const noexcept
{
    return groupid_;
}
void Groupuser::setGroupid(const int32_t &pGroupid) noexcept
{
    groupid_ = std::make_shared<int32_t>(pGroupid);
    dirtyFlag_[0] = true;
}

const int32_t &Groupuser::getValueOfUserid() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(userid_)
        return *userid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Groupuser::getUserid() const noexcept
{
    return userid_;
}
void Groupuser::setUserid(const int32_t &pUserid) noexcept
{
    userid_ = std::make_shared<int32_t>(pUserid);
    dirtyFlag_[1] = true;
}

const std::string &Groupuser::getValueOfGrouprole() const noexcept
{
    static const std::string defaultValue = std::string();
    if(grouprole_)
        return *grouprole_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Groupuser::getGrouprole() const noexcept
{
    return grouprole_;
}
void Groupuser::setGrouprole(const std::string &pGrouprole) noexcept
{
    grouprole_ = std::make_shared<std::string>(pGrouprole);
    dirtyFlag_[2] = true;
}
void Groupuser::setGrouprole(std::string &&pGrouprole) noexcept
{
    grouprole_ = std::make_shared<std::string>(std::move(pGrouprole));
    dirtyFlag_[2] = true;
}
void Groupuser::setGrouproleToNull() noexcept
{
    grouprole_.reset();
    dirtyFlag_[2] = true;
}

void Groupuser::updateId(const uint64_t id)
{
}
typename Groupuser::PrimaryKeyType Groupuser::getPrimaryKey() const
{
    return std::make_tuple(*groupid_,*userid_);
}

const std::vector<std::string> &Groupuser::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "groupid",
        "userid",
        "grouprole"
    };
    return inCols;
}

void Groupuser::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getGroupid())
        {
            binder << getValueOfGroupid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserid())
        {
            binder << getValueOfUserid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getGrouprole())
        {
            binder << getValueOfGrouprole();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Groupuser::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Groupuser::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getGroupid())
        {
            binder << getValueOfGroupid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserid())
        {
            binder << getValueOfUserid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getGrouprole())
        {
            binder << getValueOfGrouprole();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Groupuser::toJson() const
{
    Json::Value ret;
    if(getGroupid())
    {
        ret["groupid"]=getValueOfGroupid();
    }
    else
    {
        ret["groupid"]=Json::Value();
    }
    if(getUserid())
    {
        ret["userid"]=getValueOfUserid();
    }
    else
    {
        ret["userid"]=Json::Value();
    }
    if(getGrouprole())
    {
        ret["grouprole"]=getValueOfGrouprole();
    }
    else
    {
        ret["grouprole"]=Json::Value();
    }
    return ret;
}

Json::Value Groupuser::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getGroupid())
            {
                ret[pMasqueradingVector[0]]=getValueOfGroupid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserid())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserid();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getGrouprole())
            {
                ret[pMasqueradingVector[2]]=getValueOfGrouprole();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getGroupid())
    {
        ret["groupid"]=getValueOfGroupid();
    }
    else
    {
        ret["groupid"]=Json::Value();
    }
    if(getUserid())
    {
        ret["userid"]=getValueOfUserid();
    }
    else
    {
        ret["userid"]=Json::Value();
    }
    if(getGrouprole())
    {
        ret["grouprole"]=getValueOfGrouprole();
    }
    else
    {
        ret["grouprole"]=Json::Value();
    }
    return ret;
}

bool Groupuser::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("groupid"))
    {
        if(!validJsonOfField(0, "groupid", pJson["groupid"], err, true))
            return false;
    }
    else
    {
        err="The groupid column cannot be null";
        return false;
    }
    if(pJson.isMember("userid"))
    {
        if(!validJsonOfField(1, "userid", pJson["userid"], err, true))
            return false;
    }
    else
    {
        err="The userid column cannot be null";
        return false;
    }
    if(pJson.isMember("grouprole"))
    {
        if(!validJsonOfField(2, "grouprole", pJson["grouprole"], err, true))
            return false;
    }
    return true;
}
bool Groupuser::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Groupuser::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("groupid"))
    {
        if(!validJsonOfField(0, "groupid", pJson["groupid"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("userid"))
    {
        if(!validJsonOfField(1, "userid", pJson["userid"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("grouprole"))
    {
        if(!validJsonOfField(2, "grouprole", pJson["grouprole"], err, false))
            return false;
    }
    return true;
}
bool Groupuser::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Groupuser::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
